---
title: "Breast cancer proteomics data analysis [Brigham & Women's Hospital & Harvard Medical School (2012)]"
format: html
---

## Useful libraries

```{r useful-libraries, message=FALSE}
library(tidyverse)
library(normalblockr)
library(aricode)
library(clusterProfiler)
library(pathview)
library(enrichplot)
set.seed(1)
```

## Loading & formatting data

Loading proteomics data to analyse and clinical data to get cancer subtypes as covariates.

```{r data-load}
data(brca_rppa)
```

Formatting data for Normal-Block.

```{r Normal-Block-formatting}
Y          <- as.matrix(brca_rppa$expr)
X_subtype  <- model.matrix(~ 0 + PAM50_SUBTYPE, data = brca_rppa$covariates)
data_subtype <- NormalBlockData$new(Y, X_subtype)
```

## Applying Normal-Block to the data

### Running the integrated inference procedure for 1 to 40 clusters.

```{r running-normal-block}
NB_prot_subtype <- normal_block(data_subtype, blocks = 1:30)
```

### Model selection: criteria to fix the number of clusters

```{r plotting criteria}
NB_prot_subtype$plot(c("deviance", "BIC", "ICL"))
```

```{r model-selection}
selected_NB <- NB_prot_subtype$get_best_model("ICL")
paste0("ICL selects ", selected_NB$q, " clusters.")
```

## Enrichment analysis

```{r enrichment}
EntrezGeneID <-
  setNames(brca_rppa$gene_annotation$entrezGeneId,
           brca_rppa$gene_annotation$protein)
df_inter <- data.frame(
    Entrez = brca_rppa$gene_annotation$entrezGeneId,
    group  = selected_NB$clustering
  )
inter_kegg <- compareCluster(Entrez~group, data = df_inter, fun='enrichKEGG', pvalueCutoff = 0.001)
inter_kegg <- setReadable(inter_kegg, OrgDb = "org.Hs.eg.db", keyType="ENTREZID")
dotplot(inter_kegg, font.size = 8)
```
