library(MASS)

#' @description generates abundance data under the normal-block model given an
#' adequate list of parameters and a covariate matrix
#' @returns an abundance matrix Y
#' @param param list of parameters as generated by generate_parameters in
#' parameters_generation.R
#' @param X covariates matrix as generated by generate X in
#' parameters_generation.R
normal_block_data <- function(param, X){
  n <- nrow(X) ; p <- nrow(param$C) ; q <- ncol(param$C)
  W <- mvrnorm(n, mu=matrix(rep(0, q), q, 1), Sigma=param$Sigma)
  epsilon <- mvrnorm(n, mu=matrix(rep(0, p), p, 1), Sigma=param$D)
  Y = X  %*% param$B + tcrossprod(W,param$C) + epsilon
  if(max(param$kappa) > 0){
    zero_location <-matrix(data = rbinom(n * p, size = 1, prob = rep(param$kappa, each = n)),
                           nrow = n,ncol = p)
    zero_location[, colSums(zero_location) == n] <- 0
    Y[zero_location == 1] <- 0
  }
  Y
}

