#ifndef NORMALBLOCKR_NORMAL_BLOCK_MEAN_BASE_H
#define NORMALBLOCKR_NORMAL_BLOCK_MEAN_BASE_H

#include <RcppArmadillo.h>
#include <vector>
#include <cmath>
#include <memory>
#include <string>
#include "normal_block_data.h"
#include "normal_block_em_base.h"
#include "omega_estimation.h"

// Abstract base class, equivalent of the R6 class NormalBlockMeanBase
// (R/NormalBlockMeanBase.R) stripped of initialization/heuristics (done in R;
// resulting parameters are passed in at construction).
//
// Mirrors NormalBlockVarBase (normal_block_var_base.h) but for the family
// where the clustering structures the *mean* (mu_i = C B' X_i), which changes
// the state it carries: B_ is d x q (one column per cluster) and Omega_ is
// p x p (variable-level), with no per-variable noise vector. run_em() also
// runs M *then* E, matching R/NormalBlockMeanUnknownClusters.R. The
// iteration loop and the SQUAREM acceleration live in NormalBlockEMBase,
// shared with the variance-block family.
class NormalBlockMeanBase : public NormalBlockEMBase {
protected:
  const NormalBlockData& data_;
  int q_;
  arma::mat B_;      // d x q, regression coefficients (one column per cluster)
  arma::mat Omega_;  // p x p, precision matrix of the variables
  double sparsity_;
  arma::mat sparsity_weights_; // p x p
  bool accelerate_;
  std::string cov_structure_;  // "full", "diagonal" or "spherical"

  virtual void M_step() = 0;
  virtual void E_step() = 0; // no-op for known clusterings
  void em_cycle() override { M_step(); E_step(); }

  arma::mat estimate_omega(const arma::mat& Sigma_hat) const {
    return nb_omega::estimate(Sigma_hat, sparsity_, sparsity_weights_);
  }

  // Omega-specific algebra, specialized when Omega is known to be diagonal:
  // the dense p x p products below then collapse to column scalings.
  bool omega_is_diagonal() const { return cov_structure_ != "full"; }

  double log_det_omega() const {
    return omega_is_diagonal() ? arma::accu(arma::log(Omega_.diag()))
                               : arma::log_det_sympd(Omega_);
  }

  arma::mat rmult_omega(const arma::mat& M) const { // M * Omega
    if (!omega_is_diagonal()) return M * Omega_;
    arma::mat out = M;
    out.each_row() %= Omega_.diag().t();
    return out;
  }

  // Precision matrix from the M-step residuals and the variational correction
  // (a p-vector, empty for a known clustering). "diagonal"/"spherical" never
  // form the p x p cross-product: only its diagonal is needed, which is also
  // what frees them from the n > p requirement of the full covariance.
  arma::mat omega_from_residuals(const arma::mat& R_bar, const arma::vec& lambda) const {
    if (cov_structure_ == "full") {
      arma::mat Sigma = R_bar.t() * R_bar / data_.n;
      if (!lambda.is_empty()) Sigma += arma::diagmat(lambda);
      return estimate_omega(Sigma);
    }
    arma::vec s = arma::vectorise(arma::sum(arma::square(R_bar), 0)) / data_.n;
    if (!lambda.is_empty()) s += lambda;
    if (cov_structure_ == "spherical") s.fill(arma::mean(s));
    return arma::diagmat(1.0 / s);
  }

  // As in the variance-block family, sparsity excludes the acceleration; the
  // `accelerate_` flag additionally lets the caller turn it off to recover the
  // plain recursion (used by tests/testthat/test-cpp-normal-block-mean.R to
  // compare against the reference R implementation).
  bool supports_acceleration() const override { return accelerate_ && sparsity_ <= 0.0; }

  void copy_tracked_state_from(const NormalBlockMeanBase& other) {
    B_ = other.B_;
    Omega_ = other.Omega_;
  }

public:
  NormalBlockMeanBase(const NormalBlockData& data, int q,
                      const arma::mat& B0, const arma::mat& Omega0,
                      double sparsity, const arma::mat& sparsity_weights,
                      bool accelerate, const std::string& cov_structure) :
    data_(data), q_(q), B_(B0), Omega_(Omega0),
    sparsity_(sparsity), sparsity_weights_(sparsity_weights), accelerate_(accelerate),
    cov_structure_(cov_structure) {}

  virtual ~NormalBlockMeanBase() = default;

  // objective() is declared by NormalBlockEMBase. Unlike the variance-block
  // family, the lasso penalty is *not* subtracted from it here: the R side
  // adds it back through the `sparsity_term` active binding.

  const arma::mat& B() const { return B_; }
  const arma::mat& Omega() const { return Omega_; }

protected:
  // p = vec(B_, Omega_). tau is deliberately left out: it is regenerated by
  // the E-step from the extrapolated parameters, and extrapolating it would
  // take it off the simplex.
  arma::vec get_state() const override {
    return arma::join_vert(arma::vectorise(B_), arma::vectorise(Omega_));
  }

  void set_state(const arma::vec& p) override {
    arma::uword nB = B_.n_elem;
    B_     = arma::reshape(p.subvec(0, nB - 1), B_.n_rows, B_.n_cols);
    Omega_ = arma::reshape(p.subvec(nB, p.n_elem - 1), Omega_.n_rows, Omega_.n_cols);
  }

  // Cheap guard against a candidate Omega that isn't positive definite.
  // Uses a Cholesky rather than the eigendecomposition the variance-block
  // core can afford: Omega is p x p here, not q x q.
  bool state_is_feasible(const arma::vec& p) const override {
    arma::uword nB = B_.n_elem;
    if (!p.is_finite()) return false;
    arma::mat Omega_cand = arma::reshape(p.subvec(nB, p.n_elem - 1), Omega_.n_rows, Omega_.n_cols);
    if (cov_structure_ != "full") return arma::all(Omega_cand.diag() > 0.0);
    arma::mat R;
    return arma::chol(R, arma::symmatu(Omega_cand));
  }

};

#endif // NORMALBLOCKR_NORMAL_BLOCK_MEAN_BASE_H
