#ifndef NORMALBLOCKR_NORMAL_BLOCK_MEAN_BASE_H
#define NORMALBLOCKR_NORMAL_BLOCK_MEAN_BASE_H

#include <RcppArmadillo.h>
#include <vector>
#include <cmath>
#include <memory>
#include "normal_block_data.h"
#include "omega_estimation.h"

// Abstract base class, equivalent of the R6 class NormalBlockMeanBase
// (R/NormalBlockMeanBase.R) stripped of initialization/heuristics (done in R;
// resulting parameters are passed in at construction).
//
// Mirrors NormalBlockVarBase (normal_block_var_base.h) but for the family
// where the clustering structures the *mean* (mu_i = C B' X_i), which changes
// the state it carries: B_ is d x q (one column per cluster) and Omega_ is
// p x p (variable-level), with no per-variable noise vector. run_em() also
// runs M *then* E, matching R/NormalBlockMeanUnknownClusters.R.
class NormalBlockMeanBase {
protected:
  const NormalBlockData& data_;
  int q_;
  arma::mat B_;      // d x q, regression coefficients (one column per cluster)
  arma::mat Omega_;  // p x p, precision matrix of the variables
  double sparsity_;
  arma::mat sparsity_weights_; // p x p
  bool accelerate_;

  virtual void M_step() = 0;
  virtual void E_step() = 0; // no-op for known clusterings

  arma::mat estimate_omega(const arma::mat& Sigma_hat) const {
    return nb_omega::estimate(Sigma_hat, sparsity_, sparsity_weights_);
  }

  // As in the variance-block family, sparsity excludes the acceleration; the
  // `accelerate_` flag additionally lets the caller turn it off to recover the
  // plain recursion (used by tests/testthat/test-cpp-normal-block-mean.R to
  // compare against the reference R implementation).
  virtual bool supports_acceleration() const { return accelerate_ && sparsity_ <= 0.0; }

  void copy_tracked_state_from(const NormalBlockMeanBase& other) {
    B_ = other.B_;
    Omega_ = other.Omega_;
  }

public:
  NormalBlockMeanBase(const NormalBlockData& data, int q,
                      const arma::mat& B0, const arma::mat& Omega0,
                      double sparsity, const arma::mat& sparsity_weights,
                      bool accelerate) :
    data_(data), q_(q), B_(B0), Omega_(Omega0),
    sparsity_(sparsity), sparsity_weights_(sparsity_weights), accelerate_(accelerate) {}

  virtual ~NormalBlockMeanBase() = default;

  // (V)EM criterion at the current parameter values. Unlike the
  // variance-block family, the lasso penalty is *not* subtracted here: the R
  // side adds it back through the `sparsity_term` active binding.
  virtual double objective() const = 0;

  virtual std::unique_ptr<NormalBlockMeanBase> clone() const = 0;
  virtual void restore_from(const NormalBlockMeanBase& other) = 0;

  // Alternates M_step()/E_step(), recording objective() each iteration, with
  // the same SQUAREM extrapolation (Varadhan & Roland, 2008) the
  // variance-block core uses -- see normal_block_var_base.h.
  void run_em(int maxit, double tol) {
    objective_trace_.clear();
    objective_trace_.push_back(objective());
    niter_ = 0;
    if (!supports_acceleration()) {
      for (int h = 0; h < maxit; ++h) {
        M_step(); E_step();
        objective_trace_.push_back(objective());
        niter_ = h + 1;
        if (std::abs(objective_trace_[h + 1] - objective_trace_[h]) < tol) break;
      }
      return;
    }

    while (niter_ < maxit) {
      arma::vec p0 = get_state();

      M_step(); E_step();
      double obj1 = objective();
      objective_trace_.push_back(obj1);
      ++niter_;
      if (std::abs(obj1 - objective_trace_[objective_trace_.size() - 2]) < tol) return;
      if (niter_ >= maxit) return;
      arma::vec p1 = get_state();

      M_step(); E_step();
      double obj2 = objective();
      objective_trace_.push_back(obj2);
      ++niter_;
      if (std::abs(obj2 - obj1) < tol) return;
      if (niter_ >= maxit) return;
      arma::vec p2 = get_state();

      if (try_squarem_step(p0, p1, p2, obj2)) {
        double obj_acc = objective();
        objective_trace_.push_back(obj_acc);
        ++niter_;
        if (std::abs(obj_acc - obj2) < tol) return;
      }
    }
  }

  const arma::mat& B() const { return B_; }
  const arma::mat& Omega() const { return Omega_; }
  const std::vector<double>& objective_trace() const { return objective_trace_; }
  int niter() const { return niter_; }

private:
  std::vector<double> objective_trace_;
  int niter_ = 0;

  // p = vec(B_, Omega_). tau is deliberately left out: it is regenerated by
  // the E-step from the extrapolated parameters, and extrapolating it would
  // take it off the simplex.
  arma::vec get_state() const {
    return arma::join_vert(arma::vectorise(B_), arma::vectorise(Omega_));
  }

  void set_state(const arma::vec& p) {
    arma::uword nB = B_.n_elem;
    B_     = arma::reshape(p.subvec(0, nB - 1), B_.n_rows, B_.n_cols);
    Omega_ = arma::reshape(p.subvec(nB, p.n_elem - 1), Omega_.n_rows, Omega_.n_cols);
  }

  // Cheap guard against a candidate Omega that isn't positive definite.
  // Uses a Cholesky rather than the eigendecomposition the variance-block
  // core can afford: Omega is p x p here, not q x q.
  bool state_is_feasible(const arma::vec& p) const {
    arma::uword nB = B_.n_elem;
    if (!p.is_finite()) return false;
    arma::mat Omega_cand = arma::reshape(p.subvec(nB, p.n_elem - 1), Omega_.n_rows, Omega_.n_cols);
    arma::mat R;
    return arma::chol(R, arma::symmatu(Omega_cand));
  }

  bool try_squarem_step(const arma::vec& p0, const arma::vec& p1, const arma::vec& p2, double obj2) {
    arma::vec r = p1 - p0;
    arma::vec v = (p2 - p1) - r;
    double vv = arma::dot(v, v);
    if (vv < 1e-14) return false;

    double alpha = -std::sqrt(arma::dot(r, r) / vv);
    double accept_slack = 1e-8 * (1.0 + std::abs(obj2));

    std::unique_ptr<NormalBlockMeanBase> snapshot = clone();
    for (int attempt = 0; attempt < 10 && alpha < -1.0; ++attempt) {
      arma::vec p_new = p0 - 2.0 * alpha * r + (alpha * alpha) * v;
      if (state_is_feasible(p_new)) {
        set_state(p_new);
        M_step();
        E_step();
        if (state_is_feasible(get_state()) && objective() >= obj2 - accept_slack) return true;
        restore_from(*snapshot);
      }
      alpha = 0.5 * (alpha - 1.0);
    }
    return false;
  }
};

#endif // NORMALBLOCKR_NORMAL_BLOCK_MEAN_BASE_H
