# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit a normal-block model with known clusters (Rcpp/Armadillo core)
#'
#' Equivalent of the R6 class NormalBlockVarKnownClusters (R/NormalBlockVarKnownClusters.R),
#' implementing sections 2/3 (summarized in 6.1/6.2) of
#' normal_block_calculations_v2.pdf. Initialization is entirely done on the R
#' side: this function only runs the EM recursion from the parameters given.
#'
#' @param Y response matrix (n x p)
#' @param X design matrix (n x d)
#' @param C fixed cluster-indicator matrix (p x q)
#' @param B0 initial regression coefficients (d x p)
#' @param dm1_0 initial inverse variance per variable (length p)
#' @param Omega0 initial precision matrix of the blocks (q x q)
#' @param sparsity sparsity penalty applied to Omega through the graphical
#' lasso (glassoFast); 0 means an unpenalized inversion
#' @param sparsity_weights q x q matrix of per-pair penalty weights (see
#' R/NormalBlockVarBase.R, `sparsity_weights`); only used when sparsity > 0
#' @param noise_covariance either "diagonal" or "spherical"
#' @param niter maximum number of EM iterations
#' @param threshold convergence threshold on the objective increment
#' @return a list with the fitted parameters (B, dm1, Omega, gamma, mu), the
#' objective (log-likelihood) trace and the number of iterations performed
#' @noRd
NormalBlockVarKnownClusters_fit <- function(Y, X, C, B0, dm1_0, Omegaq0, sparsity, sparsity_weights, noise_covariance, niter, threshold) {
    .Call(`_normalblockr_NormalBlockVarKnownClusters_fit`, Y, X, C, B0, dm1_0, Omegaq0, sparsity, sparsity_weights, noise_covariance, niter, threshold)
}

#' Fit a normal-block model with unknown clusters (Rcpp/Armadillo core, VEM)
#'
#' Equivalent of the R6 class NormalBlockVarUnknownClusters (R/NormalBlockVarUnknownClusters.R), implementing
#' sections 4/5 (summarized in 6.3) of normal_block_calculations_v2.pdf.
#' Initialization is entirely done on the R side: this function only runs the
#' VEM recursion from the parameters given.
#'
#' @inheritParams NormalBlockVarKnownClusters_fit
#' @param C0 initial variational membership probabilities (p x q)
#' @param alpha0 initial cluster prior probabilities (length q)
#' @param M0 initial variational mean of the cluster effects (n x q)
#' @param S0 initial variational variance of the cluster effects (length q)
#' @param fixed_tau if TRUE, the variational membership probabilities are not
#' re-estimated (useful for stability selection)
#' @return a list with the fitted parameters (B, dm1, Omega, C, alpha, M, S),
#' the ELBO trace and the number of iterations performed
#' @noRd
NormalBlockVarUnknownClusters_fit <- function(Y, X, B0, dm1_0, Omegaq0, C0, alpha0, M0, S0, sparsity, sparsity_weights, noise_covariance, fixed_tau, niter, threshold) {
    .Call(`_normalblockr_NormalBlockVarUnknownClusters_fit`, Y, X, B0, dm1_0, Omegaq0, C0, alpha0, M0, S0, sparsity, sparsity_weights, noise_covariance, fixed_tau, niter, threshold)
}

#' Fit a zero-inflated normal-block model with known clusters (Rcpp/Armadillo core)
#'
#' Equivalent of the R6 class ZINormalBlockVarKnownClusters (R/ZINormalBlockVarKnownClusters.R).
#' Initialization (including the fixed zero-inflation logistic regression)
#' is entirely done on the R side: this function only runs the EM recursion
#' from the parameters given. The zero-inflation mask makes the B-update's
#' normal equations column-specific, so it is solved one column at a time
#' (see src/zi_closed_form_solvers.h).
#'
#' @param Y response matrix (n x p)
#' @param X design matrix (n x d)
#' @param zeros_bar zero-inflation mask (n x p), 1 where Y != 0, 0 where Y == 0
#' @param zi_cond_mean fixed log-likelihood contribution of the (pre-estimated)
#' zero-inflation component (private$ZI_cond_mean in R/NormalBlockVarBase.R)
#' @param C fixed cluster-indicator matrix (p x q)
#' @param B0 initial regression coefficients (d x p)
#' @param dm1_0 initial inverse variance per variable (length p)
#' @param Omega0 initial precision matrix of the blocks (q x q)
#' @param sparsity sparsity penalty applied to Omega through the graphical
#' lasso (glassoFast); 0 means an unpenalized inversion
#' @param sparsity_weights q x q matrix of per-pair penalty weights
#' @param noise_covariance either "diagonal" or "spherical"
#' @param niter maximum number of EM iterations
#' @param threshold convergence threshold on the objective increment
#' @return a list with the fitted parameters (B, dm1, Omega, gamma, mu -- gamma
#' is a q x q x n array, one posterior covariance matrix per row), the
#' log-likelihood trace and the number of iterations performed
#' @noRd
ZINormalBlockVarKnownClusters_fit <- function(Y, X, zeros_bar, zi_cond_mean, C, B0, dm1_0, Omegaq0, sparsity, sparsity_weights, noise_covariance, niter, threshold) {
    .Call(`_normalblockr_ZINormalBlockVarKnownClusters_fit`, Y, X, zeros_bar, zi_cond_mean, C, B0, dm1_0, Omegaq0, sparsity, sparsity_weights, noise_covariance, niter, threshold)
}

#' Fit a zero-inflated normal-block model with unknown clusters (Rcpp/Armadillo core, VEM)
#'
#' Equivalent of the R6 class ZINormalBlockVarUnknownClusters (R/ZINormalBlockVarUnknownClusters.R).
#' Initialization is entirely done on the R side: this function only runs
#' the VEM recursion from the parameters given. The zero-inflation mask
#' makes the B- and M-updates' normal equations column-/row-specific, so
#' both are solved through direct linear systems rather than an iterative
#' optimizer (see src/zi_closed_form_solvers.h).
#'
#' @inheritParams ZINormalBlockVarKnownClusters_fit
#' @param C0 initial variational membership probabilities (p x q)
#' @param alpha0 initial cluster prior probabilities (length q)
#' @param M0 initial variational mean of the cluster effects (n x q)
#' @param S0 initial variational variance of the cluster effects (n x q,
#' row-dependent because of the zero-inflation mask)
#' @param fixed_tau if TRUE, the variational membership probabilities are not
#' re-estimated (useful for stability selection)
#' @return a list with the fitted parameters (B, dm1, Omega, C, alpha, M, S),
#' the ELBO trace and the number of iterations performed
#' @noRd
ZINormalBlockVarUnknownClusters_fit <- function(Y, X, zeros_bar, zi_cond_mean, B0, dm1_0, Omegaq0, C0, alpha0, M0, S0, sparsity, sparsity_weights, noise_covariance, fixed_tau, niter, threshold) {
    .Call(`_normalblockr_ZINormalBlockVarUnknownClusters_fit`, Y, X, zeros_bar, zi_cond_mean, B0, dm1_0, Omegaq0, C0, alpha0, M0, S0, sparsity, sparsity_weights, noise_covariance, fixed_tau, niter, threshold)
}

